language: php
php:
- 5.6
- 7.0
- 7.1

before_script:
  - phpenv rehash
  - git clone https://github.com/c9s/GenPHP-Flavors.git flavors
  - composer install --dev
  - ./scripts/compile
  - ./genphp

script: phpunit
