language: php
php:
  - 5.3
  - 5.4

before_script:
  - phpenv rehash
  - eval `curl http://install.onionphp.org/`
  - git clone https://github.com/c9s/GenPHP-Flavors.git flavors
  - composer install --dev
  - ./scripts/compile
  - ./genphp

script: phpunit
