language: php
php:
  - 5.3.2
  - 5.3
  - 5.4

before_script:
  - pyrus install pear.php.net/PEAR
  - "curl -O https://github.com/c9s/Onion/raw/master/onion.phar"
  - phpenv rehash
  - php onion.phar -d bundle
  - ./scripts/compile.sh
  - php onion.phar -d build

script: phpunit
